version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    volumes:
      - ./data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend
  app:
    image: steckel/phantom
    ports:
      - "3000:3000"
    networks:
      - frontend
    depends_on:
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/steckel.env

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
